import React, { useState } from 'react';
import { ArrowRight, Plus, X, Check, Search, Radar, BookOpen, CalendarDays, GraduationCap, RefreshCw, ShieldCheck, Pause, Play, Bell, AlertTriangle } from 'lucide-react';
import { allHistory, passedCredits, weightedScore, gradeEstimate } from './suite-model.js';
import { catalog } from './search-model.js';
import { official, slotText } from './model.js';

const terms=['1152','1161','1162','1171','1172'];
const termLabel=value=>`${value.slice(0,3)}-${value.slice(3)}`;
function PageHeading({kicker,title,description,children}){return <div className="page-heading suite-heading"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{description}</p></div>{children}</div>;}
function Metric({label,value,unit,note}){return <div className="metric"><span>{label}</span><strong>{value}<small>{unit}</small></strong><p>{note}</p></div>;}
function Empty({title,text,action}){return <div className="suite-empty"><BookOpen size={30}/><h3>{title}</h3><p>{text}</p>{action}</div>;}

export function GraduationPage({suite,setSuite,onFind}) {
  const [program,setProgram]=useState('本系'); const [expanded,setExpanded]=useState('本系必修');
  const [draft,setDraft]=useState({name:'',credits:3,term:'1152',group:'本系必修'});
  const records=allHistory(suite), completed=passedCredits(records);
  const groups=program==='本系'?[['本系必修',60],['本系選修',24],['通識',18],['共同課程',suite.target-102]]:program==='雙主修'?[['雙主修必修',30],['雙主修選修',12]]:[['輔系必修',12],['輔系選修',6]];
  function add(e){e.preventDefault();const name=draft.name.trim();if(!name)return;if(suite.future.some(c=>c.name===name&&c.term===draft.term))return;setSuite({...suite,future:[...suite.future,{...draft,name,credits:Number(draft.credits),id:`f-${Date.now()}`}]});setDraft({...draft,name:''});}
  return <><PageHeading kicker="YOUR DEGREE, YOUR PATH" title="知道還差多少，才能安排下一步。" description="從已完成的學分出發，把本學期與未來規劃分開看。"/><div className="suite-metrics"><Metric label="已完成學分" value={completed} unit={`/ ${suite.target}`} note="只計已通過的示範紀錄"/><Metric label="本學期已選" value="18" unit="學分" note="修讀中，尚未計入畢業進度"/><Metric label="距離總學分門檻" value={Math.max(0,suite.target-completed)} unit="學分" note="仍須逐項滿足課程與其他門檻"/></div>
  <div className="degree-layout"><section className="surface"><div className="surface-head"><h2>畢業條件</h2><span className="badge amber">示範規則 · 非正式審核</span></div><div className="program-tabs">{['本系','雙主修','輔系'].map(p=><button key={p} className={p===program?'chosen':''} aria-pressed={p===program} onClick={()=>{setProgram(p);setExpanded('');}}>{p==='本系'?'資工主修':p==='雙主修'?'企管雙主修':'財金輔系'}</button>)}</div>{groups.map(([name,target])=>{const matched=records.filter(c=>c.group===name&&c.status==='已通過'),value=passedCredits(matched);return <div className="requirement" key={name}><button className="requirement-head" aria-expanded={expanded===name} onClick={()=>setExpanded(expanded===name?'':name)}><span><strong>{name}</strong><small>{value===0?'尚無已認列紀錄':`已通過 ${matched.length} 門課`}</small></span><b>{value}<small> / {target}</small></b><ArrowRight size={16}/></button><progress value={value} max={target} aria-label={`${name}完成進度`}/>{expanded===name&&<div className="requirement-details">{matched.length?matched.map(c=><p key={c.id}><Check size={13}/>{c.name}<span>{c.credits} 學分</span></p>):<p>尚無通過且符合此分類的示範紀錄。</p>}<button className="subtle" onClick={()=>onFind('',name==='本系選修'?'本系選修':name==='通識'?'通識':'全部課程')}>找相關課程 <ArrowRight size={14}/></button></div>}</div>;})}<p className="surface-note">雙主修、輔系與兼充各自審核；預排及待認列用途不會自動算成完成。</p></section><aside className="surface next-steps"><div className="surface-head"><h2>下一步</h2><GraduationCap size={20}/></div><div className="next-step"><span>01</span><div><strong>先處理必修缺口</strong><p>對照當年度課程標準，確認作業系統等必修的安排。</p></div></div><div className="next-step"><span>02</span><div><strong>留意雙主修與輔系認列</strong><p>選課用途只是意向，兼充結果以系所核准為準。</p></div></div><div className="next-step"><span>03</span><div><strong>其他畢業門檻</strong><p>英文、體育與服務學習尚待核對，不能只用總學分判定畢業。</p></div></div><div className="history-banner">這是介面示範，門檻與課程並非你的正式畢業審核結果。</div></aside></div>
  <section className="surface future-surface"><div className="surface-head"><div><h2>把未來幾學期排開</h2><p>先安排課名與學分；正式開課後再找班別與時段。</p></div><span className="badge neutral">含大四規劃</span></div><form className="future-form" onSubmit={add}><label className="field">規劃課名<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例如 作業系統"/></label><label className="field">學期<select value={draft.term} onChange={e=>setDraft({...draft,term:e.target.value})}>{terms.map(t=><option key={t} value={t}>{termLabel(t)}</option>)}</select></label><label className="field">學分<input type="number" min="0" max="10" required value={draft.credits} onChange={e=>setDraft({...draft,credits:e.target.value})}/></label><label className="field">用途<select value={draft.group} onChange={e=>setDraft({...draft,group:e.target.value})}>{['本系必修','本系選修','通識','共同課程','雙主修','輔系'].map(g=><option key={g}>{g}</option>)}</select></label><button className="primary"><Plus size={15}/>加入規劃</button></form><div className="future-board">{terms.map(t=>{const rows=suite.future.filter(c=>c.term===t);return <section className="term-column" key={t}><header><strong>{termLabel(t)}</strong><span>{rows.reduce((s,c)=>s+c.credits,0)} 學分</span></header><small>{t.startsWith('117')?'大四':'未來學期'} · 待確認開課</small>{rows.map(c=><div className="future-card" key={c.id}><div><strong>{c.name}</strong><button className="icon-button" aria-label={`移除未來規劃 ${c.name}`} onClick={()=>setSuite({...suite,future:suite.future.filter(x=>x.id!==c.id)})}><X size={13}/></button></div><p>{c.group} · {c.credits} 學分</p><label className="field">安排學期<select aria-label={`調整 ${c.name} 學期`} value={c.term} onChange={e=>setSuite({...suite,future:suite.future.map(x=>x.id===c.id?{...x,term:e.target.value}:x)})}>{terms.map(term=><option key={term} value={term}>{termLabel(term)}</option>)}</select></label><button className="subtle" onClick={()=>onFind(c.name)}>查開課 <ArrowRight size={13}/></button></div>)}{!rows.length&&<p className="term-empty">留一點空間給新的選擇。</p>}</section>;})}</div></section></>;
}

export function HistoryPage({suite,setSuite,onFind,onCurrent}){
  const [query,setQuery]=useState(''),[status,setStatus]=useState('全部'),[detail,setDetail]=useState(null);
  const records=allHistory(suite), filtered=records.filter(c=>c.name.includes(query)&&(status==='全部'||c.status===status));
  return <><PageHeading kicker="LOOK BACK, MOVE FORWARD" title="每一門課，都留下了軌跡。" description="保留完整修課紀錄；未通過的課程不計入已完成學分。"/><div className="suite-metrics"><Metric label="已完成" value={passedCredits(records)} unit="學分" note="與畢業規劃使用相同紀錄"/><Metric label="歷次加權平均" value={weightedScore(records)?.toFixed(1)} unit="分" note="含未通過紀錄，非官方 GPA"/><Metric label="本學期修讀中" value="6" unit="門" note="查看課表、筆記及成績試算"/></div><section className="surface"><div className="surface-head"><h2>修課時間軸</h2><button className="secondary" onClick={onCurrent}>查看本學期 <ArrowRight size={15}/></button></div><div className="history-controls"><label className="search-input"><Search size={16}/><input aria-label="搜尋修課紀錄" value={query} onChange={e=>setQuery(e.target.value)} placeholder="找一門修過的課"/></label><div className="program-tabs">{['全部','已通過','未通過'].map(s=><button key={s} aria-pressed={status===s} className={status===s?'chosen':''} onClick={()=>setStatus(s)}>{s}</button>)}</div></div>{!filtered.length?<Empty title="沒有符合的紀錄" text="試試其他課名，或切換紀錄狀態。" action={<button className="secondary" onClick={()=>{setQuery('');setStatus('全部');}}>清除條件</button>}/>:['1142','1141'].map(term=>{const rows=filtered.filter(c=>c.term===term);return rows.length>0&&<div className="history-term" key={term}><div className="history-term-heading"><span className="term-dot"/><h3>{termLabel(term)}</h3><span>{passedCredits(records.filter(c=>c.term===term))} 學分通過</span></div>{rows.map(c=><div key={c.id} className="history-course"><button onClick={()=>setDetail(detail?.id===c.id?null:c)} aria-expanded={detail?.id===c.id}><span className={`course-mark ${c.status==='未通過'?'orange':'blue'}`}><BookOpen size={17}/></span><span><strong>{c.name}</strong><small>{c.group} · {c.credits} 學分</small></span><span className={`badge ${c.status==='未通過'?'amber':'neutral'}`}>{c.status}</span><b>{c.score}<small> 分</small></b></button>{detail?.id===c.id&&<div className="history-course-detail"><p>{c.status==='未通過'?'此筆未計入畢業學分。保留原始紀錄，即使後續重修通過也不抹除。':'此筆已通過，依示範分類計入畢業進度。'}</p><label className="field">這門課的筆記<textarea value={suite.notes[c.id]||''} onChange={e=>setSuite({...suite,notes:{...suite.notes,[c.id]:e.target.value}})} placeholder="記下學習心得或想保留的提醒…"/></label><button className="subtle" onClick={()=>onFind(c.name)}>查詢再次開課 <ArrowRight size={14}/></button></div>}</div>)}</div>;})}</section></>;
}

export function MonitorPage({suite,setSuite,tracking,setTracking,onFind}){
  const [filter,setFilter]=useState('全部'),[log,setLog]=useState(false);
  const rows=catalog.filter(c=>tracking.includes(c.id)&&!c.historical);
  const config=c=>suite.monitor[c.id]||{paused:false,auto:false,max:3};
  const update=(c,patch)=>setSuite({...suite,monitor:{...suite.monitor,[c.id]:{...config(c),...patch}}});
  const active=suite.connection==='connected'?rows.filter(c=>!config(c).paused).length:0;
  return <><PageHeading kicker="A LITTLE LESS REFRESHING" title="把等待，交給一個清楚的清單。" description="名額、追蹤狀態與加選結果放在一起，不必來回確認。"><button className="primary" onClick={()=>onFind('')}><Plus size={16}/>找課加入</button></PageHeading><div className="monitor-banner"><Radar size={22}/><div><strong>{suite.connection==='connected'?'監控情境預覽':suite.connection==='expired'?'登入已過期，等待重新連線':'服務離線，暫停查詢'}</strong><p>所有名額與狀態均為示範，不啟動背景服務、通知或自動加選。</p></div><span className="badge blue">115-1</span></div><div className="suite-metrics"><Metric label="追蹤清單" value={rows.length} unit="門" note="與課程詳情的追蹤草稿共用"/><Metric label="示範追蹤中" value={active} unit="門" note="可逐門暫停，不影響課表預排"/><Metric label="示範額滿" value={rows.filter(c=>c.seats===0).length} unit="門" note="名額未公告另行標示"/></div><section className="surface"><div className="surface-head"><div className="program-tabs">{['全部','追蹤中','已暫停'].map(f=><button key={f} className={filter===f?'chosen':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><button className="subtle" onClick={()=>setLog(!log)} aria-expanded={log}>查看活動紀錄</button></div>{log&&<div className="activity-log"><ClockLine text="示範環境已就緒。所有操作只更新本機草稿。"/><ClockLine text={`${rows.length} 門追蹤課程；尚未向學校查詢名額。`}/></div>}{!rows.length?<Empty title="先放進一門想等的課" text="從課程詳情加入追蹤，回到這裡查看名額與狀態。" action={<button className="primary" onClick={()=>setTracking(['BA303'])}>加入額滿示範課程</button>}/>:rows.filter(c=>filter==='全部'||(filter==='已暫停')===config(c).paused).map(c=><div className="monitor-row" key={c.id}><div className="monitor-course"><span className={`course-mark ${c.color}`}><Radar size={20}/></span><div><h3>{c.name}</h3><p>{c.teacher} · {c.id} · {slotText(c)}</p></div><span className={`badge ${config(c).paused?'neutral':'blue'}`}>{config(c).paused?'已暫停':suite.connection!=='connected'?'等待連線':'示範追蹤中'}</span></div><div className="monitor-data"><div><small>模擬剩餘名額</small><strong>{c.seats==null?'未公告':c.seats===0?'額滿':`${c.seats} 人`}</strong></div><div><small>加選嘗試</small><strong>0 / {config(c).max}</strong></div><label className="switch-control"><input type="checkbox" checked={config(c).auto} onChange={e=>update(c,{auto:e.target.checked})}/>自動加選示範</label><label className="field">次數上限<select value={config(c).max} onChange={e=>update(c,{max:Number(e.target.value)})}>{[1,3,5].map(n=><option key={n} value={n}>{n} 次</option>)}</select></label></div>{config(c).auto&&<p className="history-banner">已選擇自動加選情境。原型不執行加選；正式版必須具備有效校務連線與開放時段。</p>}<div className="monitor-actions"><button className="secondary" onClick={()=>update(c,{paused:!config(c).paused})}>{config(c).paused?<Play size={14}/>:<Pause size={14}/>} {config(c).paused?'恢復追蹤':'暫停追蹤'}</button><button className="subtle" onClick={()=>onFind(c.name)}>查看課程</button><button className="subtle" onClick={()=>setTracking(tracking.filter(id=>id!==c.id))}>移除追蹤</button></div></div>)}{rows.length>0&&rows.every(c=>filter==='追蹤中'?config(c).paused:filter==='已暫停'?!config(c).paused:false)&&<Empty title="此狀態目前沒有課程" text="切換「全部」查看追蹤清單。"/>}</section></>;
}
function ClockLine({text}){return <p><span className="status-dot"/>{text}</p>;}

export function SettingsPage({suite,setSuite}){
  const [preview,setPreview]=useState(false),[message,setMessage]=useState('');
  const sync=()=>{if(suite.connection!=='connected'){setMessage('示範連線不可用，請先將連線情境切回已連線。');return;}setSuite({...suite,synced:'剛剛完成示範同步'});setMessage('已更新示範同步時間，未連線至學校或覆寫真實資料。');};
  return <><PageHeading kicker="MAKE IT YOURS" title="資料清楚，規劃才安心。" description="管理校務連線、同步狀態與個人規劃偏好。"/><div className="settings-layout"><section className="surface"><div className="surface-head"><h2>校務連線與同步</h2><ShieldCheck size={20}/></div><div className="account-preview"><div className="avatar">同</div><div><strong>示範同學</strong><p>資訊工程系 · 企管雙主修 · 財金輔系</p></div><span className={`badge ${suite.connection==='connected'?'blue':'amber'}`}>{suite.connection==='connected'?'已連線（示範）':suite.connection==='expired'?'登入已過期':'服務離線'}</span></div><label className="field connection-scenario">連線情境<select value={suite.connection} onChange={e=>setSuite({...suite,connection:e.target.value})}><option value="connected">已連線</option><option value="expired">登入已過期</option><option value="offline">服務離線</option></select></label>{suite.connection!=='connected'&&<div className="history-banner">{suite.connection==='expired'?'正式版需重新完成登入，再恢復同步；原型不收集帳號密碼。':'目前只能查看已保存資料；正式版待服務恢復後再同步。'}</div>}{['目前選課','歷年成績','初選志願'].map(name=><div className="sync-row" key={name}><span><strong>{name}</strong><small>{suite.synced}</small></span><button className="secondary" aria-label={`模擬同步${name}`} onClick={sync}><RefreshCw size={14}/>模擬同步</button></div>)}{message&&<p className="inline-notice" role="status">{message}</p>}</section><section className="surface"><div className="surface-head"><h2>通知與學分目標</h2><Bell size={19}/></div><label className="settings-toggle"><span><strong>Email 通知偏好</strong><small>僅保存偏好，不寄送通知</small></span><input type="checkbox" checked={suite.email} onChange={e=>setSuite({...suite,email:e.target.checked})}/></label><label className="field target-field">總學分目標<select value={suite.target} onChange={e=>setSuite({...suite,target:Number(e.target.value)})}><option value="128">128 學分（示範）</option><option value="132">132 學分（示範）</option></select></label><p className="surface-note">同步影響資料，偏好影響呈現。正式畢業門檻仍應依入學年度與系所規定確認。</p><div className="settings-info"><h3>GPA 與校務帳號</h3><p>此原型只展示未啟用／歷史參考狀態。正式版的帳號綁定與 GPA 授權流程須另外串接。</p></div></section></div><section className="surface import-surface"><div className="surface-head"><div><h2>匯入與核對</h2><p>資料套用前，先看新增、重複與需要確認的項目。</p></div><button className="secondary" onClick={()=>setPreview(!preview)} aria-expanded={preview}>開啟匯入預覽</button></div>{preview&&<div className="import-preview"><div className="import-row"><span className={`badge ${suite.imported?'neutral':'blue'}`}>{suite.imported?'已存在':'新增'}</span><strong>科技與倫理</strong><span>114-2 · 2 學分 · 86 分</span></div><div className="import-row"><span className="badge neutral">略過重複</span><strong>程式設計</strong><span>114-1 紀錄已存在</span></div><p>示範資料套用後，修課紀錄與畢業進度會一起更新；現有筆記與預排保留。</p><button className="primary" disabled={suite.imported} onClick={()=>setSuite({...suite,imported:true})}>{suite.imported?'已套用示範資料':'套用這 1 筆示範資料'}</button></div>}</section></>;
}

export function CourseNotebook({course,suite,setSuite}){
  const [parts,setParts]=useState([{name:'期中',weight:30,score:''},{name:'期末',weight:30,score:''},{name:'作業',weight:40,score:''}]);
  const estimate=gradeEstimate(parts);
  return <div className="course-notebook"><details><summary>課堂筆記與成績試算</summary><label className="field">課堂筆記<textarea value={suite.notes[course.id]||''} onChange={e=>setSuite({...suite,notes:{...suite.notes,[course.id]:e.target.value}})} placeholder="待辦、上課重點、報告截止日…"/></label><p className="muted">筆記自動保存在原型；試算分數只在這次詳情保留。</p><div className="grade-grid"><span>項目</span><span>權重 %</span><span>成績</span>{parts.map((p,i)=><React.Fragment key={p.name}><strong>{p.name}</strong><input aria-label={`${p.name}權重`} type="number" min="0" max="100" value={p.weight} onChange={e=>setParts(parts.map((x,j)=>j===i?{...x,weight:e.target.value}:x))}/><input aria-label={`${p.name}成績`} type="number" min="0" max="100" value={p.score} onChange={e=>setParts(parts.map((x,j)=>j===i?{...x,score:e.target.value}:x))}/></React.Fragment>)}</div><p role="status" className="grade-result">{estimate.weight!==100?`權重合計 ${estimate.weight}%，請調整為 100%。`:estimate.value==null?'填完各項成績後顯示試算。':`試算總成績 ${estimate.value.toFixed(1)} 分`}</p><p className="muted">試算不會寫入正式成績，也不影響畢業學分。</p></details></div>;
}
